import React, { useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import {
  Box,
  Card,
  CardContent,
  Typography,
  TextField,
  MenuItem,
  Button,
  Grid,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Chip,
  CircularProgress,
  Divider,
  Alert,
  Snackbar,
  Paper,
} from '@mui/material';
import {
  Assessment as ReportIcon,
  Download as DownloadIcon,
  Print as PrintIcon,
} from '@mui/icons-material';
import { format } from 'date-fns';
import { useAppDispatch, useAppSelector } from '../../app/hooks';
import { fetchCenters } from '../admin/centerSlice';
import { apiClient } from '../../utils/apiClient';
import type { Transaction, Expense, Settlement } from '../../types';
import { formatPaymentMode } from '../../utils/paymentModes';

type ReportType = 'all' | 'transactions' | 'expenses' | 'settlements';

const getTodayStr = (): string => {
  const d = new Date();
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
};

const formatCurrency = (amount: number): string =>
  new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(amount);

const formatDate = (dateStr: string): string => {
  try {
    return format(new Date(dateStr), 'MMM d, yyyy');
  } catch {
    return dateStr;
  }
};

const statusColor = (
  status: string
): 'default' | 'warning' | 'success' | 'error' => {
  switch (status) {
    case 'APPROVED':
      return 'success';
    case 'REJECTED':
      return 'error';
    case 'PENDING':
      return 'warning';
    default:
      return 'default';
  }
};

export const ReportPage: React.FC = () => {
  const dispatch = useAppDispatch();
  const { user } = useAppSelector((state) => state.auth);
  const { centers } = useAppSelector((state) => state.centers);
  const [searchParams] = useSearchParams();

  const isAdmin = user?.role === 'ADMIN';

  const today = getTodayStr();
  const [fromDate, setFromDate] = useState<string>(() => searchParams.get('from') ?? today);
  const [toDate, setToDate] = useState<string>(() => searchParams.get('to') ?? today);
  const [centerId, setCenterId] = useState<string>(() => searchParams.get('centerId') ?? '');
  const [reportType, setReportType] = useState<ReportType>('all');

  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [snackOpen, setSnackOpen] = useState(false);

  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [settlements, setSettlements] = useState<Settlement[]>([]);

  const autoGeneratedRef = useRef(false);

  useEffect(() => {
    if (isAdmin) {
      dispatch(fetchCenters());
    }
  }, [dispatch, isAdmin]);

  // Auto-generate when navigated from dashboard with URL params
  useEffect(() => {
    if (autoGeneratedRef.current) return;
    if (searchParams.get('from') && searchParams.get('to')) {
      autoGeneratedRef.current = true;
      // Defer so state is settled
      setTimeout(() => generateReport(), 0);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const buildParams = (extra?: Record<string, unknown>) => ({
    startDate: fromDate,
    endDate: toDate,
    ...(isAdmin && centerId ? { centerId } : {}),
    limit: 1000,
    page: 1,
    ...extra,
  });

  const generateReport = async () => {
    if (!fromDate || !toDate) return;

    setLoading(true);
    setGenerated(false);
    setError(null);

    let newTransactions: Transaction[] = [];
    let newExpenses: Expense[] = [];
    let newSettlements: Settlement[] = [];

    try {
      const fetchTx = reportType === 'all' || reportType === 'transactions';
      const fetchEx = reportType === 'all' || reportType === 'expenses';
      const fetchSe = reportType === 'all' || reportType === 'settlements';

      const [txRes, exRes, seRes] = await Promise.all([
        fetchTx
          ? apiClient.get('/transactions', { params: buildParams() })
          : Promise.resolve(null),
        fetchEx
          ? apiClient.get('/expenses', { params: buildParams() })
          : Promise.resolve(null),
        fetchSe
          ? apiClient.get('/settlements', { params: buildParams() })
          : Promise.resolve(null),
      ]);

      if (txRes) {
        newTransactions = txRes.data?.data?.data ?? [];
      }
      if (exRes) {
        newExpenses = exRes.data?.data?.data ?? [];
      }
      if (seRes) {
        newSettlements = seRes.data?.data?.data ?? [];
      }

      setTransactions(newTransactions);
      setExpenses(newExpenses);
      setSettlements(newSettlements);
      setGenerated(true);
    } catch (err: unknown) {
      const msg =
        (err as { response?: { data?: { message?: string } } })?.response?.data
          ?.message ?? 'Failed to generate report. Please try again.';
      setError(msg);
      setSnackOpen(true);
    } finally {
      setLoading(false);
    }
  };

  const totalIncome = transactions.reduce((sum, t) => sum + Number(t.amount ?? 0), 0);
  const totalExpenses = expenses.reduce((sum, e) => sum + Number(e.amount ?? 0), 0);
  const netProfit = totalIncome - totalExpenses;
  const settlementCount = settlements.length;

  const downloadCSV = () => {
    const rows: string[][] = [];

    const showTx = reportType === 'all' || reportType === 'transactions';
    const showEx = reportType === 'all' || reportType === 'expenses';
    const showSe = reportType === 'all' || reportType === 'settlements';

    // Summary
    rows.push(['REPORT SUMMARY']);
    rows.push([`Date Range: ${fromDate} to ${toDate}`]);
    rows.push([]);
    rows.push(['Total Income', 'Total Expenses', 'Net Profit', 'Settlement Count']);
    rows.push([
      String(totalIncome),
      String(totalExpenses),
      String(netProfit),
      String(settlementCount),
    ]);
    rows.push([]);

    if (showTx && transactions.length > 0) {
      rows.push(['TRANSACTIONS']);
      rows.push([
        '#',
        'Transaction No',
        'Date',
        'Vehicle Number',
        'Vehicle Type',
        'Income Source',
        'Amount',
        'Payment Mode',
      ]);
      transactions.forEach((t, i) => {
        rows.push([
          String(i + 1),
          t.transactionNumber,
          formatDate(t.transactionDate),
          t.vehicleNumber,
          t.vehicleType?.typeName ?? '',
          t.incomeSource?.sourceName ?? '',
          String(t.amount),
          t.paymentMode ?? '',
        ]);
      });
      rows.push([]);
    }

    if (showEx && expenses.length > 0) {
      rows.push(['EXPENSES']);
      rows.push([
        '#',
        'Expense No',
        'Date',
        'Category',
        'Vendor',
        'Amount',
        'Status',
      ]);
      expenses.forEach((e, i) => {
        rows.push([
          String(i + 1),
          e.expenseNumber,
          formatDate(e.expenseDate),
          e.category?.categoryName ?? '',
          e.vendorName ?? '',
          String(e.amount),
          e.status,
        ]);
      });
      rows.push([]);
    }

    if (showSe && settlements.length > 0) {
      rows.push(['SETTLEMENTS']);
      rows.push([
        '#',
        'Settlement No',
        'Date',
        'Total Income',
        'Total Expenses',
        'Net Amount',
        'Status',
      ]);
      settlements.forEach((s, i) => {
        rows.push([
          String(i + 1),
          s.settlementNumber,
          formatDate(s.settlementDate),
          String(s.totalIncome),
          String(s.totalExpenses),
          String(s.netAmount),
          s.status,
        ]);
      });
    }

    const csv = rows
      .map((r) =>
        r
          .map((cell) => `"${String(cell ?? '').replace(/"/g, '""')}"`)
          .join(',')
      )
      .join('\n');

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `report-${fromDate}-to-${toDate}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const showTx = generated && (reportType === 'all' || reportType === 'transactions');
  const showEx = generated && (reportType === 'all' || reportType === 'expenses');
  const showSe = generated && (reportType === 'all' || reportType === 'settlements');

  return (
    <Box sx={{ p: 3 }}>
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { font-size: 12px; }
        }
      `}</style>

      {/* Page Header */}
      <Box sx={{ display: 'flex', alignItems: 'center', mb: 3, gap: 1.5 }}>
        <ReportIcon sx={{ fontSize: 32, color: 'primary.main' }} />
        <Box>
          <Typography variant="h5" fontWeight={700}>
            Reports
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Generate date-wise financial reports for transactions, expenses, and
            settlements
          </Typography>
        </Box>
      </Box>

      {/* Filter Card */}
      <Card className="no-print" sx={{ mb: 3 }}>
        <CardContent>
          <Typography variant="subtitle1" fontWeight={600} sx={{ mb: 2 }}>
            Filter Options
          </Typography>
          <Grid container spacing={2} alignItems="center">
            <Grid item xs={12} sm={6} md={3}>
              <TextField
                label="From Date"
                type="date"
                value={fromDate}
                onChange={(e) => setFromDate(e.target.value)}
                fullWidth
                required
                InputLabelProps={{ shrink: true }}
                size="small"
              />
            </Grid>
            <Grid item xs={12} sm={6} md={3}>
              <TextField
                label="To Date"
                type="date"
                value={toDate}
                onChange={(e) => setToDate(e.target.value)}
                fullWidth
                required
                InputLabelProps={{ shrink: true }}
                size="small"
                inputProps={{ min: fromDate }}
              />
            </Grid>

            {isAdmin && (
              <Grid item xs={12} sm={6} md={3}>
                <TextField
                  select
                  label="Center"
                  value={centerId}
                  onChange={(e) => setCenterId(e.target.value)}
                  fullWidth
                  size="small"
                >
                  <MenuItem value="">All Centers</MenuItem>
                  {centers.map((c) => (
                    <MenuItem key={c.id} value={c.id}>
                      {c.centerName}
                    </MenuItem>
                  ))}
                </TextField>
              </Grid>
            )}

            <Grid item xs={12} sm={6} md={isAdmin ? 3 : 4}>
              <TextField
                select
                label="Report Type"
                value={reportType}
                onChange={(e) => setReportType(e.target.value as ReportType)}
                fullWidth
                size="small"
              >
                <MenuItem value="all">All</MenuItem>
                <MenuItem value="transactions">Transactions</MenuItem>
                <MenuItem value="expenses">Expenses</MenuItem>
                <MenuItem value="settlements">Settlements</MenuItem>
              </TextField>
            </Grid>

            <Grid item xs={12} sm={12} md={isAdmin ? 12 : 2}>
              <Button
                variant="contained"
                onClick={generateReport}
                disabled={!fromDate || !toDate || loading}
                startIcon={
                  loading ? (
                    <CircularProgress size={18} color="inherit" />
                  ) : (
                    <ReportIcon />
                  )
                }
                sx={{ minWidth: 160 }}
              >
                {loading ? 'Generating...' : 'Generate Report'}
              </Button>
            </Grid>
          </Grid>
        </CardContent>
      </Card>

      {/* Results */}
      {generated && (
        <Box>
          {/* Action Buttons */}
          <Box
            className="no-print"
            sx={{ display: 'flex', justifyContent: 'flex-end', gap: 1, mb: 2 }}
          >
            <Button
              variant="outlined"
              startIcon={<DownloadIcon />}
              onClick={downloadCSV}
              size="small"
            >
              Download CSV
            </Button>
            <Button
              variant="outlined"
              startIcon={<PrintIcon />}
              onClick={() => window.print()}
              size="small"
            >
              Print
            </Button>
          </Box>

          {/* Summary Card */}
          <Card sx={{ mb: 3 }}>
            <CardContent>
              <Typography variant="subtitle1" fontWeight={700} sx={{ mb: 2 }}>
                Summary — {formatDate(fromDate)} to {formatDate(toDate)}
              </Typography>
              <Grid container spacing={2}>
                <Grid item xs={6} sm={3}>
                  <Paper
                    variant="outlined"
                    sx={{ p: 2, textAlign: 'center', borderRadius: 2 }}
                  >
                    <Typography variant="caption" color="text.secondary">
                      Total Income
                    </Typography>
                    <Typography
                      variant="h6"
                      fontWeight={700}
                      color="success.main"
                    >
                      {formatCurrency(totalIncome)}
                    </Typography>
                  </Paper>
                </Grid>
                <Grid item xs={6} sm={3}>
                  <Paper
                    variant="outlined"
                    sx={{ p: 2, textAlign: 'center', borderRadius: 2 }}
                  >
                    <Typography variant="caption" color="text.secondary">
                      Total Expenses
                    </Typography>
                    <Typography
                      variant="h6"
                      fontWeight={700}
                      color="error.main"
                    >
                      {formatCurrency(totalExpenses)}
                    </Typography>
                  </Paper>
                </Grid>
                <Grid item xs={6} sm={3}>
                  <Paper
                    variant="outlined"
                    sx={{ p: 2, textAlign: 'center', borderRadius: 2 }}
                  >
                    <Typography variant="caption" color="text.secondary">
                      Net Profit
                    </Typography>
                    <Typography
                      variant="h6"
                      fontWeight={700}
                      color={netProfit >= 0 ? 'success.main' : 'error.main'}
                    >
                      {formatCurrency(netProfit)}
                    </Typography>
                  </Paper>
                </Grid>
                <Grid item xs={6} sm={3}>
                  <Paper
                    variant="outlined"
                    sx={{ p: 2, textAlign: 'center', borderRadius: 2 }}
                  >
                    <Typography variant="caption" color="text.secondary">
                      Settlement Count
                    </Typography>
                    <Typography variant="h6" fontWeight={700}>
                      {settlementCount}
                    </Typography>
                  </Paper>
                </Grid>
              </Grid>
            </CardContent>
          </Card>

          {/* Transactions Table */}
          {showTx && (
            <Card sx={{ mb: 3 }}>
              <CardContent>
                <Typography variant="subtitle1" fontWeight={700} sx={{ mb: 1 }}>
                  Transactions ({transactions.length})
                </Typography>
                <Divider sx={{ mb: 2 }} />
                {transactions.length === 0 ? (
                  <Alert severity="info">No transactions found for this period.</Alert>
                ) : (
                  <TableContainer>
                    <Table size="small">
                      <TableHead>
                        <TableRow sx={{ bgcolor: 'grey.50' }}>
                          <TableCell>#</TableCell>
                          <TableCell>Transaction No</TableCell>
                          <TableCell>Date</TableCell>
                          <TableCell>Vehicle</TableCell>
                          <TableCell>Income Source</TableCell>
                          <TableCell align="right">Amount</TableCell>
                          <TableCell>Payment Mode</TableCell>
                        </TableRow>
                      </TableHead>
                      <TableBody>
                        {transactions.map((t, i) => (
                          <TableRow key={t.id} hover>
                            <TableCell>{i + 1}</TableCell>
                            <TableCell>
                              <Typography variant="body2" fontFamily="monospace">
                                {t.transactionNumber}
                              </Typography>
                            </TableCell>
                            <TableCell>{formatDate(t.transactionDate)}</TableCell>
                            <TableCell>
                              <Typography variant="body2">
                                {t.vehicleNumber}
                              </Typography>
                              {t.vehicleType && (
                                <Typography
                                  variant="caption"
                                  color="text.secondary"
                                >
                                  {t.vehicleType.typeName}
                                </Typography>
                              )}
                            </TableCell>
                            <TableCell>
                              {t.incomeSource?.sourceName ?? '—'}
                            </TableCell>
                            <TableCell align="right">
                              <Typography
                                variant="body2"
                                fontWeight={600}
                                color="success.main"
                              >
                                {formatCurrency(Number(t.amount))}
                              </Typography>
                            </TableCell>
                            <TableCell>
                              {t.paymentMode ? (
                                <Chip
                                  label={formatPaymentMode(t.paymentMode)}
                                  size="small"
                                  variant="outlined"
                                />
                              ) : (
                                '—'
                              )}
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </TableContainer>
                )}
              </CardContent>
            </Card>
          )}

          {/* Expenses Table */}
          {showEx && (
            <Card sx={{ mb: 3 }}>
              <CardContent>
                <Typography variant="subtitle1" fontWeight={700} sx={{ mb: 1 }}>
                  Expenses ({expenses.length})
                </Typography>
                <Divider sx={{ mb: 2 }} />
                {expenses.length === 0 ? (
                  <Alert severity="info">No expenses found for this period.</Alert>
                ) : (
                  <TableContainer>
                    <Table size="small">
                      <TableHead>
                        <TableRow sx={{ bgcolor: 'grey.50' }}>
                          <TableCell>#</TableCell>
                          <TableCell>Expense No</TableCell>
                          <TableCell>Date</TableCell>
                          <TableCell>Category</TableCell>
                          <TableCell>Vendor</TableCell>
                          <TableCell align="right">Amount</TableCell>
                          <TableCell>Status</TableCell>
                        </TableRow>
                      </TableHead>
                      <TableBody>
                        {expenses.map((e, i) => (
                          <TableRow key={e.id} hover>
                            <TableCell>{i + 1}</TableCell>
                            <TableCell>
                              <Typography variant="body2" fontFamily="monospace">
                                {e.expenseNumber}
                              </Typography>
                            </TableCell>
                            <TableCell>{formatDate(e.expenseDate)}</TableCell>
                            <TableCell>
                              {e.category?.categoryName ?? '—'}
                            </TableCell>
                            <TableCell>{e.vendorName ?? '—'}</TableCell>
                            <TableCell align="right">
                              <Typography
                                variant="body2"
                                fontWeight={600}
                                color="error.main"
                              >
                                {formatCurrency(Number(e.amount))}
                              </Typography>
                            </TableCell>
                            <TableCell>
                              <Chip
                                label={e.status}
                                size="small"
                                color={statusColor(e.status)}
                              />
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </TableContainer>
                )}
              </CardContent>
            </Card>
          )}

          {/* Settlements Table */}
          {showSe && (
            <Card sx={{ mb: 3 }}>
              <CardContent>
                <Typography variant="subtitle1" fontWeight={700} sx={{ mb: 1 }}>
                  Settlements ({settlements.length})
                </Typography>
                <Divider sx={{ mb: 2 }} />
                {settlements.length === 0 ? (
                  <Alert severity="info">
                    No settlements found for this period.
                  </Alert>
                ) : (
                  <TableContainer>
                    <Table size="small">
                      <TableHead>
                        <TableRow sx={{ bgcolor: 'grey.50' }}>
                          <TableCell>#</TableCell>
                          <TableCell>Settlement No</TableCell>
                          <TableCell>Date</TableCell>
                          <TableCell align="right">Total Income</TableCell>
                          <TableCell align="right">Total Expenses</TableCell>
                          <TableCell align="right">Net Amount</TableCell>
                          <TableCell>Status</TableCell>
                        </TableRow>
                      </TableHead>
                      <TableBody>
                        {settlements.map((s, i) => (
                          <TableRow key={s.id} hover>
                            <TableCell>{i + 1}</TableCell>
                            <TableCell>
                              <Typography variant="body2" fontFamily="monospace">
                                {s.settlementNumber}
                              </Typography>
                            </TableCell>
                            <TableCell>{formatDate(s.settlementDate)}</TableCell>
                            <TableCell align="right">
                              <Typography
                                variant="body2"
                                fontWeight={600}
                                color="success.main"
                              >
                                {formatCurrency(Number(s.totalIncome))}
                              </Typography>
                            </TableCell>
                            <TableCell align="right">
                              <Typography
                                variant="body2"
                                fontWeight={600}
                                color="error.main"
                              >
                                {formatCurrency(Number(s.totalExpenses))}
                              </Typography>
                            </TableCell>
                            <TableCell align="right">
                              <Typography
                                variant="body2"
                                fontWeight={700}
                                color={
                                  s.netAmount >= 0
                                    ? 'success.main'
                                    : 'error.main'
                                }
                              >
                                {formatCurrency(Number(s.netAmount))}
                              </Typography>
                            </TableCell>
                            <TableCell>
                              <Chip
                                label={s.status}
                                size="small"
                                color={statusColor(s.status)}
                              />
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </TableContainer>
                )}
              </CardContent>
            </Card>
          )}
        </Box>
      )}

      {/* Error Snackbar */}
      <Snackbar
        open={snackOpen}
        autoHideDuration={5000}
        onClose={() => setSnackOpen(false)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert
          severity="error"
          onClose={() => setSnackOpen(false)}
          sx={{ width: '100%' }}
        >
          {error}
        </Alert>
      </Snackbar>
    </Box>
  );
};

export default ReportPage;
